#!/bin/bash

if [ $# -ne 3 ]; then
        echo "Enter three numbers"
elif [ $1 -eq $2 ] && [ $1 -eq $3 ]; then
        echo "All numbers are equal"
elif [ $1 -gt $2 ] && [ $1 -gt $3 ]; then
        echo "$1 is greater"
elif [ $2 -gt $3 ]; then
        echo "$2 is greater"
else
        echo " $3 is greater"
fi

