#!/bin/bash

if [ -f $1 ]; then
        echo "The $1 is a file"
        if [ -r $1 ]; then
                echo "The file has read permission"
        else
                echo "The file doesn't have read permission"
        fi
        if [ -w $1 ]; then
                echo "The file has write permission"
        else
                echo "The file doesn't have write permission"
        fi
        if [ -x $1 ]; then
                echo "The file has execute permission"
        else
                echo "The file doesn't have execute permission"
        fi

else
        echo "the $1 is a directory"
        if [ -r $1 ]; then
                echo "The dir has read permission"
        else
                echo "The dir doesn't have read permission"
        fi

fi
